#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#                  Jeremie Dimino, Jane Street Europe                   #
#                                                                       #
#   Copyright 2016 Jane Street Group LLC                                #
#                                                                       #
#   All rights reserved.  This file is distributed under the terms of   #
#   the GNU Lesser General Public License version 2.1, with the         #
#   special exception on linking described in the file ../LICENSE.      #
#                                                                       #
#########################################################################

BASEDIR=../..
MAIN_MODULE=test
C_FILES=stubs

include $(BASEDIR)/makefiles/Makefile.one
include $(BASEDIR)/makefiles/Makefile.common
